public enum Category {
    HOUSING, TRANSPORTATION, FOOD, HOUSEHOLD, CLOTHING,
    HEALTH, INSURANCE, PERSONAL, EDUCATION, SAVINGS, GIFTS,
    ENTERTAINMENT,SALARY, INVESTING, SELLING, OTHERS,
}
